Fix some configs, implement wleave well

diff --git a/.config/hypr/scripts/logoutlaunch b/.config/hypr/scripts/logoutlaunch
--- a/.config/hypr/scripts/logoutlaunch
+++ b/.config/hypr/scripts/logoutlaunch
@@ -7,51 +7,43 @@ then
     exit 0
 fi
 
-# set file variables
-ScrDir=`dirname $(realpath $0)`
-source $ScrDir/globalcontrol
-wLayout="$HOME/.config/wleave/layout"
-wlTmplt="$HOME/.config/wleave/style.css"
+if [ ! -f "$HOME/.config/wleave/gen_style.css" ]; then
+    # set file variables
+    ScrDir=`dirname $(realpath $0)`
+    source $ScrDir/globalcontrol
+    wLayout="$HOME/.config/wleave/layout"
+    wlTmplt="$HOME/.config/wleave/style.css"
 
-if [ ! -f $wLayout ] || [ ! -f $wlTmplt ] ; then
-    echo "ERROR: Config $1 not found..."
-    exit 1;
+    if [ ! -f $wLayout ] || [ ! -f $wlTmplt ] ; then
+        echo "ERROR: Config $1 not found..."
+        exit 1;
+    fi
+
+    # detect monitor res
+    x_mon=$(hyprctl -j monitors | jq '.[] | select(.focused==true) | .width')
+    y_mon=$(hyprctl -j monitors | jq '.[] | select(.focused==true) | .height')
+    hypr_scale=$(hyprctl -j monitors | jq '.[] | select (.focused == true) | .scale' | sed 's/\.//')
+
+
+    # scale config layout and style
+    wlColms=6
+    export mgn=$(( y_mon * 38 / hypr_scale ))
+    export hvr=$(( y_mon * 33 / hypr_scale ))
+
+    # scale font size
+    export fntSize=$(( y_mon * 2 / 100 ))
+
+    # detect gtk system theme
+    export BtnCol="white"
+    export WindBg="rgba(0,0,0,0.5)"
+
+    # eval hypr border radius
+    export active_rad=$(( hypr_border * 5 ))
+    export button_rad=$(( hypr_border * 8 ))
+
+    # eval config files
+    (envsubst < $wlTmplt) > $HOME/.config/wleave/gen_style.css
 fi
 
-# detect monitor res
-x_mon=$(hyprctl -j monitors | jq '.[] | select(.focused==true) | .width')
-y_mon=$(hyprctl -j monitors | jq '.[] | select(.focused==true) | .height')
-hypr_scale=$(hyprctl -j monitors | jq '.[] | select (.focused == true) | .scale' | sed 's/\.//')
-
-
-# scale config layout and style
-case $1 in
-    1)  wlColms=6
-        export mgn=$(( y_mon * 28 / hypr_scale ))
-        export hvr=$(( y_mon * 23 / hypr_scale )) ;;
-    2)  wlColms=2
-        export x_mgn=$(( x_mon * 35 / hypr_scale ))
-        export y_mgn=$(( y_mon * 25 / hypr_scale ))
-        export x_hvr=$(( x_mon * 32 / hypr_scale ))
-        export y_hvr=$(( y_mon * 20 / hypr_scale )) ;;
-esac
-
-# scale font size
-export fntSize=$(( y_mon * 2 / 100 ))
-
-# detect gtk system theme
-export BtnCol=`[ "$gtkMode" == "dark" ] && ( echo "white" ) || ( echo "black" )`
-export WindBg=`[ "$gtkMode" == "dark" ] && ( echo "rgba(0,0,0,0.5)" ) || ( echo "rgba(255,255,255,0.5)" )`
-
-
-export wbarTheme="${gtkTheme}"
-
-# eval hypr border radius
-export active_rad=$(( hypr_border * 5 ))
-export button_rad=$(( hypr_border * 8 ))
-
-# eval config files
-wlStyle=`envsubst < $wlTmplt`
-
 # launch wleave
-wleave -b $wlColms -c 0 -r 0 -m 0 --layout $wLayout --css <(echo "$wlStyle") --protocol layer-shell
+wleave -b $wlColms -c 0 -r 0 -m 0 --layout $wLayout --css $HOME/.config/wleave/gen_style.css --protocol layer-shell
